### ISSUE TITLE
BeerSong.java Standards

### ISSUE THREAD

**Issue by LiamTheCoolDude** [DaVinciTachyon/JavaPractice#1]
Please check your tabbing and indenting as mentioned below

public class BeerSong
{
  public static void main(String[] args)
  {
    //Declarations
    **int beerNum;** //Tab to make more easily readable, variable
    **String word;** //Tab to make more easily readable, variable

    //Initialisations
    **beerNum = 99;** //Tab to make more easily readable, variable
    **word = "bottles";** //Tab to make more easily readable, variable

    //Song
    while (beerNum > 0)
    {
      System.out.println(beerNum + " " +
        word + " of beer on the wall.");
      System.out.println(beerNum + " " +
        word + " of beer.");
      System.out.println("Take one down.");
      System.out.println("Pass it around.");
      beerNum--;
      if (beerNum == 1) word = "bottle";
      if (beerNum > 0) System.out.println(beerNum + " " +
        word + " of beer on the wall.\n");
      else System.out.println("No more bottles of beer on the wall.\n");
    }
  }
}

**Comment by DaVinciTachyon** [comment]
Liam, there is an issue when you upload, some of the tab are withheld.

**Comment by LiamTheCoolDude** [comment]
ok,sorry
